import Head from 'next/head'
import Image from 'next/image'
import data from '../data.json' assert {type: 'json'}
import Table from '../components/Table'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className='Home'>
      <Head>
        <title>Atomic Kicks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Atomic Kicks</h1>
      <main>
        <Table />
      </main>
    </div>
  )
}
